#!/bin/bash

# Welcome to your first bash script

# creating varible

hello_world='Hello World!'
current_dir=$(pwd)
readonly unchange_value='white'

unchange_value='blue'

echo "$hello_world, The current directory is ${current_dir} and the text color is $unchange_value"