#!/bin/bash

department=("computer science" "electical engineering" "medical lab" "mechanical engineering")

call_function(){
    for i in "${department[@]}";
    do
        if [[ $i == "computer science" ]];
        then
            echo "this is $i department"

        elif [[ $i == "electical engineering" ]];
        then
            echo "this is $i department"

        elif [[ $i == "medical lab" ]];
        then
            
            echo "this is $i department"

        elif [[ $i == "mechanical engineering" ]];
        then
            echo "this is $i department"

        else
            echo "No match found"
        fi
    done
}

call_function