#!/bin/bash

# Print values in an services array using for loops


services=("public cloud" "private cloud" "IaaS" "SaaS" "PaaS") 

for i in "${services[@]}"
do
   echo $i
done

call_out=$(pwd)

echo "$call_out"
