#!/bin/bash

# A script that will ask for a number and print out a message depending on the value. 

read -p "Enter a number: " n
case $n in
    1|2) 
        echo "it is number $n";;
    [3-9]) 
        echo "number 3 through 9";;
    aa) 
        echo "characters";;
    *.txt) 
        echo "$n!. it is a txt extension";;
    *) 
        echo "Other";;
esac
    