#!/bin/bash

# A script that will create a civo instance.

setup() { 
    # Install civo cli
    curl -sL https://civo.com/get | sudo bash

    # Add civo api key for authentication
    civo apikey add Demo_Test <api-key>
    echo "Api key added successfully."
    echo -e "\n\n"
}




# Print out available civo regions
print_out_regions() {
    regions_array=($( civo region ls | head -n 10))
    for i in "${regions_array[@]}"
    do
       echo "$i"
    done
    echo -e "\n\n"
}





# select a region
pick_region() {
    local region_exists=false
    while [[ "$region_exists" = false ]];  do #Run the following statement if the condition is true
        print_out_regions #calling the print out region function
        read -p "Enter your region: " selected_region #reading an input
        for j in "${regions_array[@]}" #loop through the regions_array from the print out region function
        do
            if [[ "$selected_region" == "$j" ]]; then 
                region_exists=true
                echo "changing the current region to $selected_region"
                civo region current "$selected_region" #change the region to the value of the selected_Region input
                break
            else
                continue
            fi
        done
    done
    echo -e "\n\n"
}

# list available civo instance sizes 

list_avil_sizes () {
    sizes_array=($( civo size ls | head -n 10))
    for k in "${sizes_array[@]}"
    do
        echo "$k"
    done
    echo -e "\n\n"
}

# create a civo instance using the selected sizes 

create_civo_instance() {
    local sizes_exist=false
    while [[ $sizes_exist = false ]];
    do
        list_avil_sizes
        read -p "Enter your civo instance size: " selected_size
        for x in "${sizes_array[@]}"
        do
            if [[ $selected_size == "$x" ]];
            then
                sizes_exist=true
                echo -e "\n\n creating civo instance ......"
                civo instance create --hostname=bash-demo --size "$selected_size"  --diskimage=ubuntu-focal --initialuser=root
                break
            else
                continue
            fi
        done
    done
    echo -e "\n\n"
}

setup
print_out_regions
pick_region
list_avil_sizes
create_civo_instance
