#!/bin/bash

# A script that allows users to quickly upload files
# to a specified cloud storage solution, providing a simple and seamless 
# upload experience similar to popular storage services.


setup() { 
    # Install aws cli
    sudo yum install aws-cli

    # configure your aws cli

    aws configure
    echo "Successfully configured!"

}

# create an s3 bucket and list the available bucket in your region

create_s3_bucket(){

    #create s3 bucket

    aws s3 mb s3://technical-project

    echo "s3 bucket successfully created!"

    # list the available s3 bucket
    aws s3 ls

}

install_s3cmd_tool(){
    # install s3cmd tool

    sudo yum update && yum --enablerepo epel-testing install s3cmd

    # configure s3cmd tool

    s3cmd --configure
}

upload_files_store(){

    # create a for loop to enable user to upload selected file or all the files
    declare -a arr=($@)
    for i in ${arr[@]}
    do

    #check if it is a file
    if [[ -f "$i" ]];
    then

        file_exists=$(aws s3 ls s3://technical-project | grep "$i")
        if [[ -n $file_exists  ]];
        then

            read -p "File $i already exists. What would you like to do? (o)verwrite, (s)kip " choice
            case $choice in
            o | O)
                 pv "$i" | s3cmd --host=s3-eu-north-1.amazonaws.com  --host-bucket=s3://technical-project put --acl-public "$i" s3://technical-project
                 echo "$i file  overwritten successfully"
                 ;;
            s | S)
                 echo "Skipping $i"
                 ;;
            esac

        else
            while true;
            do

              read -p "Do you want to upload $i file: y | n " upload_file
              if [[ $upload_file =~ [yY] ]];
              then

                  pv "$i" | s3cmd --host=s3-eu-north-1.amazonaws.com  --host-bucket=s3://technical-project put --acl-public "$i" s3://technical-project
                  echo "Successfully uploaded $i"
                  break 1

              elif [[ $upload_file =~ [nN] ]];
              then
                  echo "Okay. Skipping $i"
                  break

              else
                  echo "You didn't select any choice. 0 file Uploaded." 

              fi
            done
       fi
    else
        echo "No file found. It might be a directory"

    fi
    done
}



file_nae=("create_resource_group" "create_storage_instance" "hello-dummy.txt")


setup
create_s3_bucket
install_s3cmd_tool
upload_files_store ${file_nae[@]}

