#!/bin/bash

echo "Enter your grade: "
read mark
result=$((9 * 2))

if (( $mark >= 90 )); 
then
   echo "Excellent!. Grade A+"
   echo "$((mark * result)) is the total percentage"
elif (( $mark < 90 && mark >= 80 ));
then
   echo "Very good!. Grade A"

else 
   echo "Very Poor Grade. Work harder next term"
fi
